### ISSUE TITLE
"?return_to=/projects" seems to be ignoring sonar.web.context 

### ISSUE THREAD

**Issue by tonihoang** [sonar-auth-oidc/sonar-auth-oidc#55]
When I am redirected form my OIDC provider I get returned to {mydomain}/projects, which is not found.

Shouldn't it take the sonar.web.context into account?

I have not found anything in code except:

https://github.com/vaulttec/sonar-auth-oidc/blob/84019fb037abc6df54e2b90ae46c9957a5e2abe1/src/main/java/org/vaulttec/sonarqube/auth/oidc/AutoLoginFilter.java#L39

but this is hardcoding "/projects" I assume it should contain the config.getBaseUrl()?

-->
```
private static final String OIDC_URL = "/sessions/init/" + OidcIdentityProvider.KEY + "?return_to=" + config.getBaseUrl() + "/projects";
```
to be correct?

As I am unable to test it right now I did not create a PR yet.

**Comment by tjuerge** [comment]
Thanks for spotting that.
